/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaGuideRouteImport } from './routes/visa-guide'
import { Route as Supervisor4RouteImport } from './routes/supervisor4'
import { Route as Supervisor3RouteImport } from './routes/supervisor3'
import { Route as Supervisor2RouteImport } from './routes/supervisor2'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImmigrationRouteImport } from './routes/immigration'
import { Route as EmployeeLiteRouteImport } from './routes/employee-lite'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as AssignmentRequestRouteImport } from './routes/assignment-request'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsAppIdRouteImport } from './routes/reports.$appId'
import { Route as CaseCaseIdRouteImport } from './routes/case.$caseId'

const VisaGuideRoute = VisaGuideRouteImport.update({
  id: '/visa-guide',
  path: '/visa-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const Supervisor4Route = Supervisor4RouteImport.update({
  id: '/supervisor4',
  path: '/supervisor4',
  getParentRoute: () => rootRouteImport,
} as any)
const Supervisor3Route = Supervisor3RouteImport.update({
  id: '/supervisor3',
  path: '/supervisor3',
  getParentRoute: () => rootRouteImport,
} as any)
const Supervisor2Route = Supervisor2RouteImport.update({
  id: '/supervisor2',
  path: '/supervisor2',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmigrationRoute = ImmigrationRouteImport.update({
  id: '/immigration',
  path: '/immigration',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeLiteRoute = EmployeeLiteRouteImport.update({
  id: '/employee-lite',
  path: '/employee-lite',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentRequestRoute = AssignmentRequestRouteImport.update({
  id: '/assignment-request',
  path: '/assignment-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAppIdRoute = ReportsAppIdRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => ReportsRoute,
} as any)
const CaseCaseIdRoute = CaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/assignment-request': typeof AssignmentRequestRoute
  '/employee': typeof EmployeeRoute
  '/employee-lite': typeof EmployeeLiteRoute
  '/immigration': typeof ImmigrationRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/search': typeof SearchRoute
  '/supervisor': typeof SupervisorRoute
  '/supervisor2': typeof Supervisor2Route
  '/supervisor3': typeof Supervisor3Route
  '/supervisor4': typeof Supervisor4Route
  '/visa-guide': typeof VisaGuideRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/reports/$appId': typeof ReportsAppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/assignment-request': typeof AssignmentRequestRoute
  '/employee': typeof EmployeeRoute
  '/employee-lite': typeof EmployeeLiteRoute
  '/immigration': typeof ImmigrationRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/search': typeof SearchRoute
  '/supervisor': typeof SupervisorRoute
  '/supervisor2': typeof Supervisor2Route
  '/supervisor3': typeof Supervisor3Route
  '/supervisor4': typeof Supervisor4Route
  '/visa-guide': typeof VisaGuideRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/reports/$appId': typeof ReportsAppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/assignment-request': typeof AssignmentRequestRoute
  '/employee': typeof EmployeeRoute
  '/employee-lite': typeof EmployeeLiteRoute
  '/immigration': typeof ImmigrationRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/search': typeof SearchRoute
  '/supervisor': typeof SupervisorRoute
  '/supervisor2': typeof Supervisor2Route
  '/supervisor3': typeof Supervisor3Route
  '/supervisor4': typeof Supervisor4Route
  '/visa-guide': typeof VisaGuideRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/reports/$appId': typeof ReportsAppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/assignment-request'
    | '/employee'
    | '/employee-lite'
    | '/immigration'
    | '/login'
    | '/profile'
    | '/reports'
    | '/search'
    | '/supervisor'
    | '/supervisor2'
    | '/supervisor3'
    | '/supervisor4'
    | '/visa-guide'
    | '/case/$caseId'
    | '/reports/$appId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/assignment-request'
    | '/employee'
    | '/employee-lite'
    | '/immigration'
    | '/login'
    | '/profile'
    | '/reports'
    | '/search'
    | '/supervisor'
    | '/supervisor2'
    | '/supervisor3'
    | '/supervisor4'
    | '/visa-guide'
    | '/case/$caseId'
    | '/reports/$appId'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/assignment-request'
    | '/employee'
    | '/employee-lite'
    | '/immigration'
    | '/login'
    | '/profile'
    | '/reports'
    | '/search'
    | '/supervisor'
    | '/supervisor2'
    | '/supervisor3'
    | '/supervisor4'
    | '/visa-guide'
    | '/case/$caseId'
    | '/reports/$appId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AssignmentRequestRoute: typeof AssignmentRequestRoute
  EmployeeRoute: typeof EmployeeRoute
  EmployeeLiteRoute: typeof EmployeeLiteRoute
  ImmigrationRoute: typeof ImmigrationRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SearchRoute: typeof SearchRoute
  SupervisorRoute: typeof SupervisorRoute
  Supervisor2Route: typeof Supervisor2Route
  Supervisor3Route: typeof Supervisor3Route
  Supervisor4Route: typeof Supervisor4Route
  VisaGuideRoute: typeof VisaGuideRoute
  CaseCaseIdRoute: typeof CaseCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa-guide': {
      id: '/visa-guide'
      path: '/visa-guide'
      fullPath: '/visa-guide'
      preLoaderRoute: typeof VisaGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor4': {
      id: '/supervisor4'
      path: '/supervisor4'
      fullPath: '/supervisor4'
      preLoaderRoute: typeof Supervisor4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor3': {
      id: '/supervisor3'
      path: '/supervisor3'
      fullPath: '/supervisor3'
      preLoaderRoute: typeof Supervisor3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor2': {
      id: '/supervisor2'
      path: '/supervisor2'
      fullPath: '/supervisor2'
      preLoaderRoute: typeof Supervisor2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immigration': {
      id: '/immigration'
      path: '/immigration'
      fullPath: '/immigration'
      preLoaderRoute: typeof ImmigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-lite': {
      id: '/employee-lite'
      path: '/employee-lite'
      fullPath: '/employee-lite'
      preLoaderRoute: typeof EmployeeLiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignment-request': {
      id: '/assignment-request'
      path: '/assignment-request'
      fullPath: '/assignment-request'
      preLoaderRoute: typeof AssignmentRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$appId': {
      id: '/reports/$appId'
      path: '/$appId'
      fullPath: '/reports/$appId'
      preLoaderRoute: typeof ReportsAppIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteChildren {
  ReportsAppIdRoute: typeof ReportsAppIdRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsAppIdRoute: ReportsAppIdRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AssignmentRequestRoute: AssignmentRequestRoute,
  EmployeeRoute: EmployeeRoute,
  EmployeeLiteRoute: EmployeeLiteRoute,
  ImmigrationRoute: ImmigrationRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SearchRoute: SearchRoute,
  SupervisorRoute: SupervisorRoute,
  Supervisor2Route: Supervisor2Route,
  Supervisor3Route: Supervisor3Route,
  Supervisor4Route: Supervisor4Route,
  VisaGuideRoute: VisaGuideRoute,
  CaseCaseIdRoute: CaseCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
